modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="http://my.issue.tracker/"

[[mods]]
modId="modularexplosions"
version="1.0.0"
displayName="Modular Explosions"
updateJSONURL="http://myurl.me/"
displayURL="https://cinqfoiscinq.fr/"
logoFile="modularexplosions.png"
credits="Merci à ceux qui utilisent du beurre pour faire cuire leurs steaks."
authors="Twiguinou, Hickacou"
description='''
Un mod développé pour la MFFJam 2020 !
'''

[[dependencies.modularexplosions]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.modularexplosions]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
